### ISSUE TITLE
add quiet-mode setting (no output)

### ISSUE THREAD

**Issue by lyova24** [lengthylyova/nugit#11]
```yaml
# nugit.yaml example

settings:
  quite: True # makes nugit ignore jobs output

jobs:
  greeting:
    required: True
    run:
      - echo "Hi from Nugit!" # actual command
```
