### ISSUE TITLE
Ability to configure pre-push

### ISSUE THREAD

**Issue by lyova24** [lengthylyova/nugit#22]
### Add the ability to describe in the config not only the `pre-commit`, but also the `pre-push`. Such a feature will allow describing other scripts for *Git*.

**Comment by lyova24** [comment]
### Expecting something like this:
```yaml
# nugit.yaml

settings:
  timeout: 0.5

pre-commit:
  jobs:
    greetings:
      - echo "Hello from Nugit!"

pre-push:
  jobs:
    say-bye-to-code:
      - echo "bye bye code!"    
```

**Comment by lyova24** [comment]
Another variation
```yaml
# nugit.yaml

settings:
  timeout: 0.5

jobs:
  greetings:
    on: [pre-commit, pre-push]
    run:
      - echo "Hello from Nugit!"

  say-bye-to-code:
    on: [pre-push]
    run:
      - echo "bye bye code!"    
```
